# Generated by Django 5.2.1 on 2025-07-08 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ResumeApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="photos/"),
        ),
    ]
